### ISSUE TITLE
support homebrew linux installation

### ISSUE THREAD

**Issue by nicks** [vmware-tanzu/buildkit-cli-for-kubectl#108]
**What steps did you take and what happened**

On Linux:

```
$ brew install kubectl-buildkit
...
Error: Empty installation
```

**What did you expect to happen**

I expected kubectl-buildkit to install successfully

**Other details**

As far as I can tell, Darwin is hard-coded in the Homebrew formula here:
https://github.com/vmware-tanzu/buildkit-cli-for-kubectl/blob/main/HomebrewFormula/kubectl-buildkit.rb#L17

Would you accept a PR to make this work on Linux? Seems like it'd be easy to add.

**Vote on this request**

This is an invitation to the community to vote on issues.  Use the "smiley face" up to the right of this comment to vote.

- :+1: "I would like to see this bug fixed as soon as possible"
- :-1: "There are more important bugs to focus on right now"

**Comment by dhiltgen** [comment]
> Would you accept a PR to make this work on Linux? Seems like it'd be easy to add.

Yes please!   We'd love a PR to fix up the Brew formula.
