### ISSUE TITLE
windows files are not .exe

### ISSUE THREAD

**Issue by juliostanley** [vmware-tanzu/buildkit-cli-for-kubectl#45]
**What steps did you take and what happened**
Downloaded the release into windows, and extracted into a path for $env:PATH, kubectl build was not recognized, but if I change the extension of the binaries to .exe, then kubectl build works against a k3s cluster

**What did you expect to happen**
kubectl build is recognaized and works

**Environment Details:**
Windows 10
kubectl provided by docker installation

- 0.10 (use `kubectl buildkit version`)
- k3s 1.19 (use `kubectl version`)
- docker (via k3d)
- unsure (didn't go into k3s), but prob not related

**Builder Logs**
N/A

**Dockerfile**
N/A

**Vote on this request**

This is an invitation to the community to vote on issues.  Use the "smiley face" up to the right of this comment to vote.

- :+1: "I would like to see this bug fixed as soon as possible"
- :-1: "There are more important bugs to focus on right now"

**Comment by dhiltgen** [comment]
Well that's embarrassing - lets get this fixed ASAP so Windows users can use the builds.

**Comment by juliostanley** [comment]
**Fyi**

Using scoop this is what a manifest looks like (with the workaround):
https://github.com/liifi/workstation/blob/master/bucket/kubectl-buildkit.json#L11

So for instance this will work with current pre release artifact (if not yet changed)
`scoop install https://github.com/liifi/workstation/blob/master/bucket/kubectl-buildkit.json`

I'll maybe make a pull request to the scoop bucket later (after the artifacts/release include .exe)
https://github.com/ScoopInstaller/Main/tree/master/bucket

So others can do
```
scoop install kubectl-buildkit
kubectl build # ready to go
```

**Comment by dhiltgen** [comment]
Once #48 is merged, I'll see if there are any other critical fixes we want to get in, then cut a v0.1.1 release so we can get the fixed up binaries published.

**Comment by dhiltgen** [comment]
@juliostanley I just created a release that fixes the `.exe` suffix (along with a few other accumulated fixes.)  I had a few glitches with CI, so the version is now v0.1.2.
