### ISSUE TITLE
Add support for http_proxy and https_proxy environment inside the deployment pods

### ISSUE THREAD

**Issue by gkalele** [vmware-tanzu/buildkit-cli-for-kubectl#54]
**Describe the problem/challenge you have**

All nodes in our Kubernetes cluster need to go through an http_proxy/https_proxy.
The build fails attempting to get the manifest for the "FROM <name>:<tag>".

The ENV operation in Dockerfiles to set variables during a build does not work if put prior to the first FROM line. And the manifest fetch for this FROM image fails prior to the ENV operator if specified after the FROM line.

```
 > [build 1/7] FROM docker.io/library/centos:7:
------
Error: failed to solve: rpc error: code = Unknown desc = failed to load cache key: failed to do request: Head https://registry-1.docker.io/v2/library/centos/manifests/7: dial tcp: lookup registry-1.docker.io on 10.96.0.10:53: server misbehaving
```

**Description of the solution you'd like**

In the code that makes up the Deployment object, we can inject environment variables into the pods ( maybe here in pkg/driver/kubernetes/manifest/manifest.go). Assuming that the buildkit commands in the pod can utilize the http_proxy variable from the environment.
We would also need command line arguments to allow the user to specify the variables (similar to the docker build --build-args flag, which didn't work with kubectl build by the way).

**Design/Architecture Details**

This ability to specify environment variables in the Deployment pods might be useful for other reasons also, although most will be covered by the ENV operative that works post the first FROM operation. ENV operators in the Dockerfile might not be feasible in many cases though.

**Environment Details:**

- kubectl buildkit version (use `kubectl buildkit version`)

v0.1.2

- Kubernetes version (use `kubectl version`)
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Where are you running kubernetes (e.g., bare metal, vSphere Tanzu, Cloud Provider xKS, etc.)
- Container Runtime and version (e.g. containerd `sudo ctr version` or dockerd `docker version` on one of your kubernetes worker nodes)

**Vote on this request**

This is an invitation to the community to vote on issues.  Use the "smiley face" up to the right of this comment to vote.

- :+1: "This project will be more useful if this feature were added"
- :-1: "This feature will not enhance the project in a meaningful way"

**Comment by dhiltgen** [comment]
I was looking around a little, and it looks like this might be built in already to BuildKit via build args.  I don't have a way to test this myself, but if you look at https://github.com/moby/buildkit/blob/master/frontend/dockerfile/dockerfile2llb/convert.go#L1325-L1332 it sounds like the following might work:
```
kubectl build --build-arg https_proxy=<proxy-here> -t myimage .
```

Could you give that shot?  If it does work, I'll add some docs to explain how to use this.

**Comment by florianbegusch** [comment]
@dhiltgen  had assumed so as well, as this is how to do it in a regular docker build. Sad to say it did not:
```
$ oc build --build-arg https_proxy="$HTTPS_PROXY" -t arch-all -f Dockerfile .
[+] Building 0.0s (0/0)
ERRO[0000] error sending request: Post "https://[redacted]:8443/api/v1/namespaces/buildkit--kubectl-plugin-test/pods/buildkit-84fcc97dbd-lfbx2/exec?command=buildctl&command=dial-stdio&container=buildk[+] Building 0.0s (0/0)
```

I should mention that HTTPS_PROXY and oc were set up as follows:
```
$ echo "$HTTPS_PROXY"
socks5://localhost:5555
$ type oc
oc is aliased to `HTTPS_PROXY="socks5://localhost:5555" oc'
```

**Comment by disaster37** [comment]
I have the same issue.

The `--build-arg` is usefull to set proxy whe it start to build image. But here, it failed when it pull base image (before this step).
It need to have proxy setted on buildkit deployment.

I have tested to set manually `http_proxy` and `https_proxy` on buildkit deployement. After that it work fine over proxy. But how to ask buildkit to this environment variable when it create deployement on kubernetes ?
