### ISSUE TITLE
Grpc error:  timed out waiting for server handshake

### ISSUE THREAD

**Issue by aronneagu** [vmware-tanzu/buildkit-cli-for-kubectl#64]
Hi all,

Doing 
`kubectl build` we are seeing around 7% of jobs fail with the following error
```
 kubectl build --cache-from type=local,src=cache --cache-to type=local,dest=cache --namespace gitlab-ci --push --tag registry.azurecr.io/${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA} -f services/${SERVICE_DIR}/Dockerfile .
Error: failed to get status: rpc error: code = Unavailable desc = timed out waiting for server handshake
```
I noticed that the project is using grpc 1.27.1, from 2nd Feb, while the latest release is 1.31.1

Would it be possible to bump the grpc version? Not sure if this would really solve it. Or is this a known issue?

Running on Azure AKS
Kubernetes master version 1.17.13
Kubernetes node version 1.17.7
kubectl-build version 0.1.2

Aron

**Comment by dhiltgen** [comment]
I'm not sure how to try to reproduce this failure, but I've created a PR that bumps the grpc library if you'd like to try that out.  You should be able to download a binary from https://github.com/vmware-tanzu/buildkit-cli-for-kubectl/pull/65/checks by clicking on the "Artifacts" link on the right side.

If that improves your situation, can you comment on the PR #65 ?

**Comment by aronneagu** [comment]
Thank you. I will try that binary and report back

**Comment by aronneagu** [comment]
It did not improve the situation. My feeling at this stage is that is capacity related somehow. We are running multiple builds concurrently, and maybe this is causing issues.
Thank you for the artefact. Will close the issue now

**Comment by dhiltgen** [comment]
Thanks for giving it a try!

We've seen some flakiness under stress, so this may be related, and require some additional hardening/retry logic or tuning of low-level timeouts.  It's definitely something we'll be continuing to explore.
