### ISSUE TITLE
How to build non privilege  pods?

### ISSUE THREAD

**Issue by smartaquarius10** [vmware-tanzu/buildkit-cli-for-kubectl#68]
Team,

In our case, we have to add these tags in the yaml while creating pod in kubernetes

```
securityContext:
      runAsUser: 3000
      allowPrivilegeEscalation: false
```
Currently getting this error

```
Warning TestPod-64f4149bcf FailedCreate Error creating: pods "TestPod-64f4149bcf-" is forbidden: unable to validate against any pod security policy: [spec.volumes[1]: Invalid va
 => => # lue: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]

```

Dockerfile :-->

1)
```
FROM scratch
USER 2000
COPY Dev /home/myuser/
CMD [ "/home/myuser/Dev" ]

```
2)
```
FROM scratch
RUN groupadd -r myuser && useradd -r -g myuser myuser
USER myuser
COPY Dev /home/myuser/
CMD [ "/home/myuser/Dev" ]

```
Tried both the docker files but no luck. Is there anyway to pass security context values which K8s can accept. Any possibility to set these values in dockerfile because I think, only this entry is not sufficient in my cluster

`USER 2000`

**Comment by dhiltgen** [comment]
This is related to #24 and #25.  At present there isn't a built-in pattern to handle this.  Running as non-root of course implies you wouldn't be able to load images directly into the underlying container runtime, but you could still leverage this tool to build and push to a registry.  This isn't the primary use case we're focused on for this tool, but making improvements to help this use case is a reasonable ask.

We do support `kubectl buildkit create --rootless` but it seems the back-end BuildKit implementation needs to start as root.  I tried creating a rootless builder, then patched it roughly as you specified (although I used the UID baked into the rootless BuildKit image) but it gets stuck in a crashloop.
```
% kubectl patch deployment buildkit -p '{"spec":{"template":{"spec":{"containers":[{"name":"buildkitd","securityContext":{"runAsUser": 1000,"allowPrivilegeEscalation": false}}]}}}}'
```
```
% kubectl logs buildkit-c8f9fdc7c-ljh6r
[rootlesskit:parent] error: failed to setup UID/GID map: newuidmap 12 [0 1000 1 1 100000 65536] failed: newuidmap: Could not set caps
: exit status 1
```

It looks like to make this work properly in a cluster that disallows root we'll need to explore upstream BuildKit changes (I think.)

**Comment by smartaquarius10** [comment]
Hmm. No issue I think in most of the organizations especially where shared kubernetes is hosted face such kind of issues. 

But could you please share the commands to push the image directly to registry from local machine using build kit. This thing shall also help us a lot because my few virtual machines(windows and linux) have less storage space. Installing docker on them would be little difficult. At least, I can push the package directly to registry and then pull the latest update to kubernetes via web hook.

**Comment by dhiltgen** [comment]
> But could you please share the commands to push the image directly to registry from local machine using build kit. This thing shall also help us a lot because my few virtual machines(windows and linux) have less storage space. Installing docker on them would be little difficult. At least, I can push the package directly to registry and then pull the latest update to kubernetes via web hook.

In general, use `kubectl buildkit --help` to get usage information (as well as `kubectl build --help`)

If you want the builder to run as non-root and never attempt to load the images into the container runtime on your kubernetes nodes you can pre-provision the builder with something like:

```
kubectl buildkit create --rootless
```
(If you skip this step, and just run `kubectl build` you'll get the default behavior.  This default behavior is optimized for local development where you do want the images loaded, which of course requires root and privileged pods.)

When you pass the `--push` flag to `build` it doesn't attempt to load the image into the local container runtime.  

```
kubectl build --push --tag myregistry.acme.com/jdoe/myimage:sometag .
```

**Comment by AkihiroSuda** [comment]
`allowPrivilegeEscalation` has to be true for initializing the user namespace with `newuidmap` setuid binary.

Note that even when `allowPrivilegeEscalation` is set to true, it is "substantially" set to false, as `buildkitd` and its children containers are executed in a user namespace, which disables the escalation.

**Comment by dclong** [comment]
I also encountered this issue. My company has migrated from VM to container which makes it very appealing to build Docker images on Kubernetes (as it is extremely slow to push Docker images locally). I've research a few tools for building Docker images on Kubernetes and buildkit-cli-for-kubectl looks very promising and is very intuitive to use. It would be a great improvement if non-privilege pods are leveraged to build Docker images.

**Comment by smartaquarius10** [comment]
@dhiltgen , Please correct me if I’m wrong but as per my understanding this would be difficult to achieve. The reason is that for building images through this approach, user needs some access to make there pods reaching the docker runtime which is running under the hood as a swarm for k8s. 

No matter if we use any kind of runtime but, end of the day giving normal users a privilege to build images through an application, like docker, which is more reachable to node under the wall of K8s is difficult to digest. That will bring a caution on the usage of psp and rbac which eventually adds on a loop hole in the security. 

I think making a secure tunnel for this wont be possible at least for now. Not sure though if my understanding correct or not.
