### ISSUE TITLE
nodeselector for buildkit deployment

### ISSUE THREAD

**Issue by Justin-DynamicD** [vmware-tanzu/buildkit-cli-for-kubectl#69]
I have a client that uses mixed EKS clusters in order to reduce management costs.  Typically we populate `nodeselector` in order to ensure containers end up on a compatible host and don't cause any issues.

I understand mixed architecture builds are not supported, this is a request/inquiry if its possible to add a simple `nodeselector` tag to your deployment to ensure pods end up on compatible nodes. If this is already possible I apologize for missing it in the docs.

**Comment by dhiltgen** [comment]
We don't have a formalized way to set this, however I think you could use `patch` to add that to the Deployment spec after creating the builder.

Take a look at https://github.com/vmware-tanzu/buildkit-cli-for-kubectl/issues/68#issuecomment-760568354 for some inspiration.  If you get stuck let us know and we'll try to help work out the exact syntax.

**Comment by Justin-DynamicD** [comment]
thanks for the inspiration.  Ill give it a shot and see where I land.

**Comment by Justin-DynamicD** [comment]
this appears to have worked!  I went the lazy, easy route for those curious.  I simply created the following patch file:

```
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
```

I then applied the patch with the following line:

```
kubectl patch deployment buildkit --patch "$(cat ./patch-buildkit.yaml)"
```

Thank you for the tip!
