### ISSUE TITLE
custom-config flag not working

### ISSUE THREAD

**Issue by wajdiail** [vmware-tanzu/buildkit-cli-for-kubectl#84]
**What steps did you take and what happened**

I ran this command "kubectl buildkit create --custom-config=custom-root-certs --config=buildkitd.toml"
I am getting the below error
Error: unknown flag: --custom-config

**What did you expect to happen**

I should not see an error it should build successfully 

**Environment Details:**

- kubectl buildkit version: v0.1.2
- Kubernetes version (use `kubectl version`): v1.20.4
- Where are you running kubernetes (e.g., bare metal, vSphere Tanzu, Cloud Provider xKS, etc.) : EKS
- Container Runtime and version (e.g. containerd `sudo ctr version` or dockerd `docker version` on one of your kubernetes worker nodes)

**Builder Logs**
[If applicable, an excerpt from `kubectl logs -l app=buildkit` from around the time you hit the failure may be very helpful]

**Dockerfile**
[If applicable, please include your Dockerfile or excerpts related to the failure]

**Vote on this request**

This is an invitation to the community to vote on issues.  Use the "smiley face" up to the right of this comment to vote.

- :+1: "I would like to see this bug fixed as soon as possible"
- :-1: "There are more important bugs to focus on right now"

**Comment by dhiltgen** [comment]
Sorry for the confusion on this one.  We implemented the feature, updated the README but hadn't cut a new release in a while, so the latest official release at the time (0.1.2) didn't have the new feature available.  We've just cut 0.1.3 which does contain this feature, so you should be set.  Head on over to https://github.com/vmware-tanzu/buildkit-cli-for-kubectl/releases for installation instructions to pick up the latest version.
